In [1]:
# Pandas is able to find all instances of a table on a webpage 
# Nic Cage's webpage has tables for each movie and TV show he was in
# Pull the table and write to .csv for later "consumption"

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_html('https://www.rottentomatoes.com/celebrity/nicolas_cage')

In [4]:
# should pull 2 different dfs, one of TV shows and one of movies
print(len(df))

2

In [5]:
# Movie dataframe is much longer, use just the movie one
df_lens=[len(x) for x in df]
print(df_lens)
df_cage = df[np.argmax(df_lens)]
df_cage.head()

[107, 19]

,Tomatometer®,Audience Score,Title,Credit,Box Office,Year
0,No Score Yet,No Score Yet,The Unbearable Weight of Massive Talent,Self,-,2022
1,61%,70%,Willy's Wonderland,"The Janitor (Character),Producer",$388.7K,2021
2,76%,No Score Yet,Prisoners of the Ghostland,Hero (Character),-,2021
3,28%,65%,Jiu Jitsu,Wylie (Character),-,2020
4,77%,94%,The Croods: A New Age,Grug (Voice),$58.5M,2020

In [6]:
# Rename the columns
df_cage.columns = ['Critics', 'Audience','Title','Credit','Box Office', 'Year']
df_cage.head()

,Critics,Audience,Title,Credit,Box Office,Year
0,No Score Yet,No Score Yet,The Unbearable Weight of Massive Talent,Self,-,2022
1,61%,70%,Willy's Wonderland,"The Janitor (Character),Producer",$388.7K,2021
2,76%,No Score Yet,Prisoners of the Ghostland,Hero (Character),-,2021
3,28%,65%,Jiu Jitsu,Wylie (Character),-,2020
4,77%,94%,The Croods: A New Age,Grug (Voice),$58.5M,2020

In [7]:
#Fix the data types

# Replace "No Score Yet" with 0
df_cage[['Critics', 'Audience']]=df_cage[['Critics', 'Audience']].replace('No Score Yet','0')
# Replace "%" with "" (for some reason df.replace wasn't working with %, used str.replace instead)
df_cage['Critics']=df_cage['Critics'].str.replace('%','')
df_cage['Audience']=df_cage['Audience'].str.replace('%','')
# Convert columns to numeric type
df_cage['Critics'] = pd.to_numeric(df_cage['Critics'])
df_cage['Audience'] = pd.to_numeric(df_cage['Audience'])
df_cage.head()

,Critics,Audience,Title,Credit,Box Office,Year
0,0,0,The Unbearable Weight of Massive Talent,Self,-,2022
1,61,70,Willy's Wonderland,"The Janitor (Character),Producer",$388.7K,2021
2,76,0,Prisoners of the Ghostland,Hero (Character),-,2021
3,28,65,Jiu Jitsu,Wylie (Character),-,2020
4,77,94,The Croods: A New Age,Grug (Voice),$58.5M,2020

In [8]:
# Save to .csv
df_cage.to_csv('Cage Scores.csv', index=False)